
# base directory
basedir=.

# what version is this?
ro.version=3.0-incubating

# compile time settings
build.debug=true
build.sourcelevel=7
build.deprecation=false


# The following properties (with your own appropriate values)
# are required if using the deploy-tomcat target.
#staging=../build/roller
#webapp.name=roller
catalina.home=c:/tomcat

# Path to Roller source, needed by our custom Netbeans actions
project.dir=C:/Documents and Settings/optimizer/Desktop/apache-roller-src-3.0-incubating
